---
name: ♿ Accessibility Issue
description: Report accessibility barriers or improvements needed
title: '[A11Y] '
labels: ['accessibility', 'a11y', 'needs-triage']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Accessibility is fundamental to civic tech. Help us ensure our project works for everyone in the community.

  - type: dropdown
    id: issue-type
    attributes:
      label: Accessibility Issue Type
      description: What type of accessibility issue is this?
      options:
        - Barrier for screen reader users
        - Keyboard navigation problem
        - Color contrast/visibility issue
        - Focus management problem
        - Text/content readability
        - Mobile accessibility barrier
        - Missing alternative text
        - Form accessibility issue
        - Video/audio accessibility
        - Cognitive accessibility barrier
        - Motor accessibility barrier
        - General accessibility improvement
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severely does this impact accessibility?
      options:
        - Critical - Completely blocks access for users
        - High - Major barrier, significant impact on usability
        - Medium - Moderate barrier, workarounds may exist
        - Low - Minor issue, small impact on experience
        - Enhancement - Improvement opportunity, not a barrier
    validations:
      required: true
  - type: textarea
    id: issue-description
    attributes:
      label: Accessibility Issue Description
      description: Describe the accessibility barrier or improvement needed
      placeholder: Be specific about what doesn't work and how it affects users with disabilities.
    validations:
      required: true
  - type: checkboxes
    id: affected-users
    attributes:
      label: Affected User Groups
      description: Which users are impacted by this accessibility issue?
      options:
        - label: Screen reader users (blind/vision impaired)
        - label: Keyboard-only users (motor impairments)
        - label: Users with low vision
        - label: Users with color blindness
        - label: Users with cognitive disabilities
        - label: Users with hearing impairments
        - label: Mobile device users
        - label: Users with older assistive technology
        - label: All users (general usability improvement)
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce the Barrier
      description: How can someone experience this accessibility issue?
      placeholder: |
        1. Using [assistive technology/method]
        2. Navigate to [specific page/section]
        3. Try to [specific action]
        4. Experience [accessibility barrier]
    validations:
      required: true
  - type: dropdown
    id: assistive-technology
    attributes:
      label: Assistive Technology Used
      description: What assistive technology revealed this issue?
      options:
        - Screen reader (NVDA)
        - Screen reader (JAWS)
        - Screen reader (VoiceOver)
        - Screen reader (other)
        - Keyboard-only navigation
        - Voice control software
        - Switch navigation
        - Screen magnification
        - High contrast mode
        - Mobile accessibility features
        - Other assistive technology
        - Manual accessibility testing
        - Automated accessibility tool
  - type: input
    id: technology-version
    attributes:
      label: Technology Version/Details
      description: Version of assistive technology or testing tool used
      placeholder: e.g., NVDA 2023.2, macOS VoiceOver, Chrome + keyboard only
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Accessible Behavior
      description: How should this work for users with disabilities?
      placeholder: Describe what accessible behavior should look like.
    validations:
      required: true
  - type: dropdown
    id: wcag-guideline
    attributes:
      label: WCAG 2.1 Guideline
      description: Which WCAG guideline does this relate to (if known)?
      options:
        - 1.1 Text Alternatives
        - 1.2 Time-based Media
        - 1.3 Adaptable
        - 1.4 Distinguishable
        - 2.1 Keyboard Accessible
        - 2.2 Enough Time
        - 2.3 Seizures and Physical Reactions
        - 2.4 Navigable
        - 2.5 Input Modalities
        - 3.1 Readable
        - 3.2 Predictable
        - 3.3 Input Assistance
        - 4.1 Compatible
        - Not sure/Multiple guidelines
        - Other accessibility standard
  - type: dropdown
    id: conformance-level
    attributes:
      label: WCAG Conformance Level
      description: What level of WCAG conformance is needed?
      options:
        - Level A (minimum)
        - Level AA (standard)
        - Level AAA (enhanced)
        - Not sure
  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested Solution
      description: Do you have ideas for how to fix this accessibility issue?
      placeholder: |
        - Technical approach: [specific implementation]
        - Content changes: [text/structure modifications]
        - Design changes: [visual/interaction modifications]
        - Alternative solutions: [other approaches to consider]
  - type: checkboxes
    id: testing-completed
    attributes:
      label: Testing Completed
      description: What accessibility testing has been done?
      options:
        - label: Manual keyboard navigation testing
        - label: Screen reader testing (NVDA/JAWS/VoiceOver)
        - label: Color contrast analysis
        - label: Automated accessibility scan (axe, WAVE, etc.)
        - label: Mobile accessibility testing
        - label: Zoom/magnification testing (200%+)
        - label: Focus visibility testing
        - label: User testing with people with disabilities
  - type: textarea
    id: testing-results
    attributes:
      label: Testing Results/Evidence
      description: What did accessibility testing reveal?
      placeholder: |
        - Automated tool results: [specific failures found]
        - Manual testing observations: [what didn't work]
        - User feedback: [if tested with people with disabilities]
        - Screenshots/recordings: [evidence of the barrier]
  - type: textarea
    id: community-impact
    attributes:
      label: Community Impact
      description: How does this accessibility issue affect the CTWR community?
      placeholder: |
        - Community members affected: [estimated number/percentage]
        - Essential services impacted: [which civic functions]
        - Equity considerations: [who is excluded by this barrier]
  - type: checkboxes
    id: priority-factors
    attributes:
      label: Priority Factors
      description: What makes this accessibility issue important to address?
      options:
        - label: Blocks essential community services
        - label: Required for legal compliance (AODA, Section 508, etc.)
        - label: High-traffic feature/page
        - label: Affects new user onboarding
        - label: Impacts vulnerable community members
        - label: Easy fix with high impact
        - label: Prerequisites for other accessibility improvements
  - type: checkboxes
    id: help-available
    attributes:
      label: Help Available
      description: How can you help address this accessibility issue?
      options:
        - label: I can help implement the fix
        - label: I can help test the solution
        - label: I can connect with users with disabilities for testing
        - label: I can provide accessibility expertise/guidance
        - label: I can help with documentation/training
        - label: I can research best practices/solutions
  - type: textarea
    id: resources-links
    attributes:
      label: Helpful Resources/Links
      description: Any resources that might help address this issue?
      placeholder: |
        - WCAG guidelines: [specific sections]
        - Code examples: [links to accessible implementations]
        - Testing tools: [recommended tools/techniques]
        - Community resources: [accessibility organizations, experts]
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information?
      placeholder: Related accessibility issues, dependencies, special considerations, etc.
