name: 📋 General Task
description: Create a general project task or work item
title: '[TASK] '
labels: ['task']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Create a task for project work that doesn't fit other issue types.

  - type: textarea
    id: task-description
    attributes:
      label: Task Description
      description: What needs to be done?
      placeholder: Clearly describe the work that needs to be completed.
    validations:
      required: true

  - type: dropdown
    id: task-category
    attributes:
      label: Task Category
      description: What type of work is this?
      options:
        - Development/Coding
        - Design/UX
        - Documentation
        - Testing
        - Community Outreach
        - Project Management
        - Research
        - Content Creation
        - Infrastructure/DevOps
        - Legal/Compliance
        - Marketing/Communications
        - Training/Education
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this task?
      options:
        - Critical - Blocks other work or Demo Day
        - High - Important for current season success
        - Medium - Good to complete this season
        - Low - Nice to have, future consideration
    validations:
      required: true

  - type: dropdown
    id: season-week
    attributes:
      label: Target Season Week
      description: When should this task be completed?
      options:
        - Week 1-3 (Project setup)
        - Week 4-6 (Development)
        - Week 7-9 (Core features)
        - Week 10-11 (Testing/refinement)
        - Week 12 (Demo Day)
        - Post-season
        - Ongoing
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know this task is complete?
      placeholder: |
        - [ ] Specific deliverable created
        - [ ] Meets quality standards
        - [ ] Reviewed by team/community
        - [ ] Documentation updated
    validations:
      required: true

  - type: checkboxes
    id: impact-areas
    attributes:
      label: Impact Areas
      description: Which areas does this task support?
      options:
        - label: Community Partner - Improves stakeholder relationships
        - label: Team Capacity - Builds team capacity or engagement
        - label: Technical Innovation - Advances technical innovation
        - label: Civic Impact - Increases community impact

  - type: dropdown
    id: effort-estimate
    attributes:
      label: Effort Estimate
      description: How much work is this task?
      options:
        - Small (1-4 hours)
        - Medium (1-2 days)
        - Large (3-5 days)
        - Extra Large (1+ weeks)
        - Unknown (needs investigation)

  - type: checkboxes
    id: skills-needed
    attributes:
      label: Skills/Expertise Needed
      description: What skills are required for this task?
      options:
        - label: Frontend development
        - label: Backend development
        - label: UI/UX design
        - label: User research
        - label: Content writing
        - label: Data analysis
        - label: Community engagement
        - label: Project management
        - label: Quality assurance/testing
        - label: Accessibility expertise
        - label: Domain knowledge (civic/government)
        - label: No special skills required

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: What needs to happen before this task can start?
      placeholder: |
        - Dependent on completion of: [other tasks/issues]
        - Requires access to: [data, systems, people]
        - Blocked by: [external factors, decisions]

  - type: checkboxes
    id: accessibility-considerations
    attributes:
      label: Accessibility Considerations
      description: Does this task have accessibility implications?
      options:
        - label: Task includes accessibility testing
        - label: Task affects user interface accessibility
        - label: Task involves content that needs to be accessible
        - label: Task requires accessibility review
        - label: No accessibility implications

  - type: textarea
    id: community-benefit
    attributes:
      label: Community Benefit
      description: How does completing this task benefit the community?
      placeholder: Explain the value this task provides to Waterloo Region residents.

  - type: checkboxes
    id: help-needed
    attributes:
      label: Help Needed
      description: What support would be helpful for this task?
      options:
        - label: Need someone to assign this to
        - label: Need technical guidance/mentorship
        - label: Need community connections/introductions
        - label: Need feedback/review from stakeholders
        - label: Need help breaking down into smaller tasks
        - label: Ready to work on independently

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information?
      placeholder: Background, references, related work, etc.
