name: ⚡ Quick Task
description: Lightweight template for fast follow-ups or chores
labels: ['task']
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: One sentence describing the change
      placeholder: 'Document workshop RSVP flow'
    validations:
      required: true
  - type: textarea
    id: done
    attributes:
      label: Definition of done
      description: Bullet list of what must be true before we close this.
      placeholder: |
        - [] Update README quick start
        - [] Share with partner for review
  - type: textarea
    id: context
    attributes:
      label: Context / links
      description: Optional background, links to Figma/Miro/Docs.
      placeholder: 'Meeting notes from Sept 23'
  - type: dropdown
    id: impact
    attributes:
      label: Impact Area (pick one)
      options:
        - No impact / N/A
        - Community Partner
        - Team Capacity
        - Technical Innovation
        - Civic Impact
    validations:
      required: false
  - type: checkboxes
    id: qa
    attributes:
      label: Quick checks
      options:
        - label: Adds or updates tests if code changes are involved
        - label: Includes accessibility considerations if user-facing
        - label: Communicated with partner/community if needed
